##Block outdated user-agents / allow good bots
#Case/Abuse: <- Add This
#Generated: Wed Sep  9 23:30:12 UTC 2026 <-Update this
#Version: 1.0
<IfModule mod_rewrite.c>
RewriteEngine On

# Allow Screaming Frog SEO Spider, Amazonbot, Bingbot, GeedoShopProductFinder, Chrome-Lighthouse, StatusCake, UptimeRobot and Pingdom
RewriteCond %{HTTP_USER_AGENT} "Screaming Frog SEO Spider|Amazonbot|Bingbot|GeedoShopProductFinder|Chrome-Lighthouse|StatusCake|UptimeRobot|Pingdom" [NC]
RewriteRule ^ - [L]

# Allow Google official verification and testing tools
RewriteCond %{HTTP_USER_AGENT} "Googlebot|Google-InspectionTool|Storebot-Google|GoogleOther|Google-Extended|GoogleImageProxy|AdsBot-Google|AdsBot-Google-Mobile|Mediapartners-Google" [NC]
RewriteRule ^ - [L]

# --- Allow Facebook / Instagram / Tik-tok in-app / Samsung browsers ---
RewriteCond %{HTTP_USER_AGENT} "FB_IAB|FBAV|FBAN/FB4A|FBAN/FBIOS|MetaIAB|Instagram|musical_ly|TikTokSpider|ByteDanceWebview|SamsungBrowser|Samsung" [NC]
RewriteRule ^ - [L]

# --- Allow Microsoft Office (Outlook/Word) and Amasty FPC Warmer ---
RewriteCond %{HTTP_USER_AGENT} "ms-office|MSOffice|Amasty_Fpc" [NC]
RewriteRule ^ - [L]

# Allow Chrome/67.* (Sucuri scanner) and Chrome/86.* (Google Indexer)
RewriteCond %{HTTP_USER_AGENT} "Chrome/(67|86)\." [NC]
RewriteRule ^ - [L]

# --- Outdated Desktop Browsers ---
RewriteCond %{HTTP_USER_AGENT} "(Chrome|HeadlessChrome|Firefox|Edg|Edge|OPR|Opera)/([1-9]|[1-8][0-9]|9[0-9])\.\d+" [NC,OR]
RewriteCond %{HTTP_USER_AGENT} "(Chrome|HeadlessChrome|Firefox)/10[0-7]\." [NC,OR]
RewriteCond %{HTTP_USER_AGENT} Firefox/1[0-3][0-9](?:[.\s]|$) [NC,OR]
RewriteCond %{HTTP_USER_AGENT} "Edge/1([0-3][0-9]|4[0-5][0-9])" [NC,OR]
RewriteCond %{HTTP_USER_AGENT} "Mozilla/[3-4]" [NC,OR]
RewriteCond %{HTTP_USER_AGENT} "Trident/[3-5]\." [NC,OR]
RewriteCond %{HTTP_USER_AGENT} "MSIE [1-9]\." [NC,OR]
RewriteCond %{HTTP_USER_AGENT} "Windows (NT [4-5]|95|98)" [NC,OR]
RewriteCond %{HTTP_USER_AGENT} "\(.*; U;" [NC,OR]
RewriteCond %{HTTP_USER_AGENT} "Version/1[0-9]" [NC,OR]

# --- Outdated Mobile Browsers ---
RewriteCond %{HTTP_USER_AGENT} "CriOS/([1-9]|[1-9][0-9])\.[0-9]" [NC,OR]
RewriteCond %{HTTP_USER_AGENT} "CriOS/10[0-7]\." [NC,OR]
RewriteCond %{HTTP_USER_AGENT} "Opera (Mini|Mobi)/[1-6]" [NC,OR]
RewriteCond %{HTTP_USER_AGENT} "Android [1-5]\." [NC,OR]
RewriteCond %{HTTP_USER_AGENT} "CPU ((iPhone|iPad) )?OS [1-9]_" [NC,OR]

# --- Abusive Chrome/Firefox activity ---
RewriteCond %{HTTP_USER_AGENT} "(Chrome|HeadlessChrome)/(11[7-9]|1[1-2][0-6]|129|13[0-6]|139|14[2-5])\." [NC,OR]
RewriteCond %{HTTP_USER_AGENT} "Firefox/(1[1-2][0-9]|13[0-6]|14[2-3])\." [NC,OR]
RewriteCond %{HTTP_USER_AGENT} "FxiOS/(1[1-2][0-9]|13[0-6]|14[2-3])\." [NC,OR]

# --- AI Crawlers ---
RewriteCond %{HTTP_USER_AGENT} "meta-webindexer|meta-externalagent|OAI-SearchBot|ChatGPT-User|GPTBot" [NC,OR]

# --- Abusive Tools --
RewriteCond %{HTTP_USER_AGENT} "Go-http-client|okhttp|python-httpx|Apache-HttpClient" [NC,OR]

# --- Abusive Crawler --
RewriteCond %{HTTP_USER_AGENT} "AliyunSecBot/Aliyun" [NC]

# If any match occurs, deny access
RewriteRule ^.* - [F,L]

##Lastest badboy - Linux Chrome/
# Block Chrome 149 only when Linux appears in the UA
RewriteCond %{HTTP_USER_AGENT} "Linux" [NC]
RewriteCond %{HTTP_USER_AGENT} "Chrome/14[0-9]" [NC]
RewriteRule ^ - [F,L]

##Block Empty User-agent
RewriteCond %{HTTP_USER_AGENT} ^$ [OR]
RewriteCond %{HTTP_USER_AGENT} ^none$ [NC,OR]
RewriteCond %{HTTP_USER_AGENT} ^null$ [NC,OR]
RewriteCond %{HTTP_USER_AGENT} ^unknown$ [NC]
RewriteRule ^ - [F,L]

</IfModule>
